language: php

sudo: false

cache:
  directories:
    - bin
    - vendor

php:
  - 7.0
  - 5.6
  - 5.5

env:
  matrix:
    - COMPOSER_OPTIONS="--prefer-lowest"
    - COMPOSER_OPTIONS=""

before_install:
  - phpenv config-rm xdebug.ini

  - composer self-update

install:
  - composer update --prefer-source $COMPOSER_OPTIONS

before_script:
  - test/app/console doctrine:database:create
  - test/app/console doctrine:schema:create

script:
  - composer validate --strict

  - bin/phpunit
