language: php

cache:
  directories:
    - bin
    - vendor

php:
  - 7.0
  - 5.6
  - 5.5

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""


before_script:
  - composer update --prefer-source PREFER_LOWEST
  - test/app/console doctrine:database:create
  - test/app/console doctrine:schema:create

script:
  - bin/phpunit test
