language: php

cache:
  directories:
    - bin
    - vendor

php:
  - 7.0
  - 5.6
  - 5.5

matrix:
  allow_failures:
    - php: 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""


before_script:
  - composer update --prefer-source PREFER_LOWEST

script:
  - bin/phpunit test
