language: php

sudo: false

cache:
    directories:
        - bin
        - vendor

php:
    - 7.2
    - 7.1

env:
    matrix:
        - PREFER_LOWEST=""
        - PREFER_LOWEST="--prefer-lowest"

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist $PREFER_LOWEST

before_script:
    - test/app/console doctrine:schema:update --force -vvv

script:
    - composer validate --strict

    - bin/phpunit

jobs:
    include:
        -   stage: Test PHPUnit 7
            php: 7.1

            install:
                - composer require phpunit/phpunit:dev-master phpunit/php-code-coverage:dev-master phpunit/php-timer:dev-master phpunit/php-token-stream:dev-master phpunit/phpunit-mock-objects:dev-master --no-interaction --update-with-all-dependencies --prefer-dist

            script:
                - bin/phpunit
